BUSINESS_RULES = [
    {
        "rule_code": "STATEMENT_BALANCE_MISMATCH",
        "title": "Descuadre entre saldo inicial, depósitos, retiros y saldo final",
        "description": "Se activa cuando el estado de cuenta no cumple la igualdad saldo inicial + depósitos - retiros = saldo final o cuando el propio origen marca saldo incorrecto.",
        "origin": "sistema_origen",
        "severity": "critica",
        "applies_to": "estado_cuenta",
        "auto_detectable": True,
        "keywords": ["saldo", "descuadre", "estado de cuenta", "saldo correcto"],
        "normative_basis": "Control operativo del conciliador y validación bancaria básica",
        "recommendation": "Revisar archivo fuente, parser bancario, movimientos faltantes o duplicados y recalcular saldos.",
    },
    {
        "rule_code": "HEADER_WITHOUT_MOVEMENTS",
        "title": "Estado de cuenta cargado sin movimientos hijos",
        "description": "Existe cabecera de estado de cuenta pero no quedaron movimientos normalizados asociados.",
        "origin": "sistema_origen",
        "severity": "alta",
        "applies_to": "estado_cuenta",
        "auto_detectable": True,
        "keywords": ["cabecera", "sin movimientos", "pdf", "parser"],
        "normative_basis": "Control de integridad de carga",
        "recommendation": "Validar nomenclatura, carpeta de origen, archivo dañado o extractor bancario.",
    },
    {
        "rule_code": "MISSING_MOVEMENT_DATE",
        "title": "Movimiento sin fecha",
        "description": "El movimiento no tiene fecha de operación identificable.",
        "origin": "operativa",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["fecha", "movimiento", "nulo"],
        "normative_basis": "Trazabilidad mínima para conciliación y corte",
        "recommendation": "Revisar parser del banco y archivo fuente; no conciliar hasta tener fecha válida.",
    },
    {
        "rule_code": "MISSING_DESCRIPTION",
        "title": "Movimiento sin descripción o concepto",
        "description": "El movimiento carece de descripción/concepto suficiente para rastreo operativo.",
        "origin": "operativa",
        "severity": "media",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["descripcion", "concepto", "vacio"],
        "normative_basis": "Trazabilidad operativa",
        "recommendation": "Complementar evidencia con referencia, folio, archivo fuente u origen operativo.",
    },
    {
        "rule_code": "MISSING_REFERENCE",
        "title": "Movimiento sin referencia o folio",
        "description": "No existe referencia, folio o campo equivalente para cruzar el movimiento con otras fuentes.",
        "origin": "operativa",
        "severity": "media",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["referencia", "folio", "cruce"],
        "normative_basis": "Trazabilidad para conciliación entre fuentes",
        "recommendation": "Complementar con sistema de referencias, Odoo, Ecobro o fuente operativa aplicable.",
    },
    {
        "rule_code": "UNRECONCILED_MOVEMENT",
        "title": "Movimiento no conciliado",
        "description": "El movimiento aparece en el dataset como no conciliado.",
        "origin": "operativa",
        "severity": "media",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["no conciliado", "conciliacion", "pendiente"],
        "normative_basis": "Estado operativo de conciliación",
        "recommendation": "Priorizar por monto, antigüedad y relación con estados de cuenta con descuadre.",
    },
    {
        "rule_code": "ZERO_AMOUNT_MOVEMENT",
        "title": "Movimiento sin importe",
        "description": "El movimiento no trae depósito ni retiro, o ambos están en cero.",
        "origin": "operativa",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["monto cero", "deposito", "retiro"],
        "normative_basis": "Integridad de transacción bancaria",
        "recommendation": "Revisar si es fila vacía, totalizador o error de parseo.",
    },
    {
        "rule_code": "BOTH_DEPOSIT_AND_WITHDRAWAL",
        "title": "Movimiento con depósito y retiro simultáneos",
        "description": "Un mismo registro trae importes de depósito y retiro mayores a cero.",
        "origin": "operativa",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["deposito", "retiro", "simultaneo"],
        "normative_basis": "Integridad de estructura bancaria",
        "recommendation": "Confirmar layout del banco y si el parser mezcló columnas.",
    },
    {
        "rule_code": "NEGATIVE_SIGN_VALUE",
        "title": "Importe con signo inconsistente",
        "description": "Hay importes negativos en campos que deberían llegar como magnitud positiva por columna.",
        "origin": "operativa",
        "severity": "media",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["signo", "negativo", "importe"],
        "normative_basis": "Normalización de layout bancario",
        "recommendation": "Homologar signo y tipo de movimiento antes de conciliar.",
    },
    {
        "rule_code": "OUTSIDE_PERIOD_RANGE",
        "title": "Movimiento fuera del rango del estado de cuenta",
        "description": "La fecha del movimiento cae fuera del periodo del estado de cuenta al que está asociado.",
        "origin": "operativa",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["periodo", "fecha", "corte"],
        "normative_basis": "Corte y congruencia documental",
        "recommendation": "Revisar si el movimiento fue asignado al archivo equivocado o si el banco incluyó arrastres.",
    },
    {
        "rule_code": "DUPLICATE_HEURISTIC",
        "title": "Posible duplicidad de movimiento",
        "description": "Se detectan movimientos repetidos por banco, cuenta, fecha, tipo, importe y descripción normalizada.",
        "origin": "operativa",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["duplicado", "movimiento repetido", "doble"],
        "normative_basis": "Prevención de doble conciliación y doble contabilización",
        "recommendation": "Confirmar si son pagos legítimos recurrentes o si hubo duplicidad de ingestión/consulta.",
    },
    {
        "rule_code": "FILENAME_PATTERN_WARNING",
        "title": "Ruta o nomenclatura de archivo no homologada",
        "description": "La ruta o el nombre del archivo no siguen el patrón operativo esperado para estados de cuenta.",
        "origin": "sistema_origen",
        "severity": "media",
        "applies_to": "archivo",
        "auto_detectable": True,
        "keywords": ["nextcloud", "nomenclatura", "ruta", "archivo"],
        "normative_basis": "Control de carga documental y homologación operativa",
        "recommendation": "Corregir carpeta, nombre y homologación antes de reprocesar.",
    },
    {
        "rule_code": "POTENTIAL_INTERCOMPANY_TRANSFER",
        "title": "Posible transferencia intercompañía o entre cuentas del grupo",
        "description": "El texto del movimiento sugiere traspaso entre entidades del grupo, por lo que debe ser conciliable por empresa pero no ingreso consolidado.",
        "origin": "propuesta_contable",
        "severity": "alta",
        "applies_to": "movimiento",
        "auto_detectable": True,
        "keywords": ["traspaso", "transferencia", "intercompany", "grupo"],
        "normative_basis": "NIF B-8 / IFRS 10: eliminación de transacciones intragrupo en estados financieros consolidados",
        "recommendation": "Clasificar como transferencia entre entidades/cuentas del grupo y evitar doble reconocimiento de ingreso.",
    },
{
    "rule_code": "NO_RESPONSIBLE_ASSIGNED",
    "title": "Cuenta sin responsable asignado",
    "description": "La cuenta no tiene responsable asociado en el catálogo operativo de la filial.",
    "origin": "operativa",
    "severity": "media",
    "applies_to": "cuenta",
    "auto_detectable": True,
    "keywords": ["responsable", "catalogo", "cuenta", "filial"],
    "normative_basis": "Control operativo y segregación de responsabilidades",
    "recommendation": "Completar assignments.csv para poder enrutar incidencias y revisión.",
},
    {
        "rule_code": "INTERCOMPANY_NOT_REVENUE",
        "title": "Las operaciones intragrupo no son ingreso consolidado",
        "description": "Las transferencias entre filiales o cuentas del mismo grupo pueden ser conciliables por entidad, pero deben eliminarse al consolidar para evitar duplicidad de ingresos.",
        "origin": "propuesta_contable",
        "severity": "critica",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["intragrupo", "intercompany", "ingreso", "duplicidad"],
        "normative_basis": "NIF B-8 / IFRS 10",
        "recommendation": "Etiquetar estas operaciones y excluirlas del reconocimiento de ingreso consolidado.",
    },
    {
        "rule_code": "CASHFLOW_CLASSIFICATION",
        "title": "Clasificación de flujos de efectivo",
        "description": "Los movimientos de efectivo deben clasificarse adecuadamente y no compensarse indebidamente entre sí.",
        "origin": "propuesta_contable",
        "severity": "media",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["flujo de efectivo", "clasificacion", "deposito", "retiro"],
        "normative_basis": "NIF B-2 / IAS 7",
        "recommendation": "Separar operación, inversión y financiamiento cuando aplique; no netear movimientos sin sustento normativo.",
    },
    {
        "rule_code": "REVENUE_GROSS_NET_COMMISSIONS",
        "title": "Ingreso bruto vs comisiones y retenciones",
        "description": "Cuando existan depósitos netos de comisiones de proveedores, debe evaluarse la presentación bruta o neta y la comisión no debe ocultar el ingreso real sin análisis de principal/agente.",
        "origin": "propuesta_contable",
        "severity": "alta",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["comision", "bruto", "neto", "toku", "netpay", "femsa"],
        "normative_basis": "NIF D-1 / IFRS 15",
        "recommendation": "Separar el ingreso del gasto/comisión y documentar el criterio contable aplicado.",
    },
    {
        "rule_code": "NO_OFFSETTING_PRESENTATION",
        "title": "No compensar activos, pasivos, ingresos o gastos sin base expresa",
        "description": "La compensación contable o de presentación sin soporte puede ocultar diferencias y distorsionar reportes.",
        "origin": "propuesta_contable",
        "severity": "alta",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["offsetting", "compensacion", "presentacion"],
        "normative_basis": "NIF A-7 / IAS 1",
        "recommendation": "Presentar de forma separada y solo compensar cuando una norma lo permita expresamente.",
    },
    {
        "rule_code": "ACCRUAL_AND_CUTOFF",
        "title": "Devengación y corte del periodo",
        "description": "Los movimientos deben reconocerse y explicarse en el periodo correcto, evitando arrastres o cortes operativos incorrectos.",
        "origin": "propuesta_contable",
        "severity": "alta",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["devengacion", "corte", "periodo"],
        "normative_basis": "NIF A-6",
        "recommendation": "Revisar fecha valor, fecha operación y política de corte para evitar conciliaciones cruzadas entre meses.",
    },
    {
        "rule_code": "RESTRICTED_CASH_PRESENTATION",
        "title": "Presentación de efectivo restringido",
        "description": "Cuando existan restricciones sobre cuentas o saldos, debe evaluarse su presentación separada del efectivo disponible.",
        "origin": "propuesta_contable",
        "severity": "media",
        "applies_to": "contabilidad",
        "auto_detectable": False,
        "keywords": ["efectivo restringido", "cash", "restriccion"],
        "normative_basis": "NIF C-1, NIF A-7",
        "recommendation": "Identificar restricciones y separar presentación de efectivo disponible vs restringido.",
    },
]
